spring:
  application:
    name: PicMuUp
  datasource:
    url: jdbc:mysql://localhost:3306/picmuup_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  timezone: Asia/Seoul
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true